[project]
name = "sumai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Daniel Rashba", email = "danirdd92@users.noreply.github.com" }
]
requires-python = ">=3.13.7"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "feedparser>=6.0.14",
    "google-antigravity>=0.1.14",
    "httpx>=0.28.1",
    "python-dateutil>=2.9.0.post0",
    "pyyaml>=6.0.3",
]

[project.scripts]
sumai = "sumai:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
